# Generated by Django 6.1.1 on 2026-09-15 03:10

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=40)),
                ('target', models.CharField(max_length=120)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_kg', models.FloatField()),
                ('sd_kg', models.FloatField()),
                ('n', models.PositiveIntegerField()),
                ('measured_on', models.DateField()),
            ],
            options={
                'ordering': ['-measured_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('logger', 'Logger'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='logger', max_length=20)),
                ('pair_code', models.CharField(max_length=8, unique=True)),
                ('token', models.CharField(default=core.models.new_hex_token, max_length=64)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(default='campus', max_length=40)),
                ('junkshop_rates_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('recoverable', models.BooleanField(default=False)),
                ('colour', models.CharField(default='#888888', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.FloatField()),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.calibration')),
            ],
        ),
        migrations.CreateModel(
            name='SackLog',
            fields=[
                ('id_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('fill', models.CharField(choices=[('full', 'Full'), ('two_thirds', 'Two-thirds'), ('half', 'Half')], default='full', max_length=12)),
                ('method', models.CharField(choices=[('C', 'Counted and calibrated'), ('W', 'Weighed'), ('V', 'Volume-estimated'), ('I', 'Imputed')], default='C', max_length=1)),
                ('weighed_kg', models.FloatField(blank=True, null=True)),
                ('logged_at', models.DateTimeField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('location_verified', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('voided', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.device')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_by', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('sacklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.sacklog')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.site'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='core.site'),
        ),
        migrations.CreateModel(
            name='SourceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('denominator_type', models.CharField(choices=[('persons', 'Persons per day'), ('meals', 'Meals served per day'), ('room_nights', 'Room-nights per day')], default='persons', max_length=20)),
                ('denominator_value', models.FloatField(default=1)),
                ('qr_token', models.CharField(default=core.models.new_hex_token, max_length=32, unique=True)),
                ('public_facing', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sacklog',
            name='source_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='core.sourcearea'),
        ),
        migrations.AddField(
            model_name='sacklog',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stream'),
        ),
        migrations.CreateModel(
            name='PurityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_checked', models.PositiveIntegerField()),
                ('items_wrong', models.PositiveIntegerField()),
                ('main_contaminant', models.CharField(blank=True, max_length=120)),
                ('checked_at', models.DateTimeField()),
                ('by_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.device')),
                ('source_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purity_checks', to='core.sourcearea')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stream')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddField(
            model_name='calibration',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stream'),
        ),
        migrations.CreateModel(
            name='DeclaredPurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('reason', models.CharField(max_length=200)),
                ('declared_by', models.CharField(max_length=80)),
                ('declared_on', models.DateField()),
                ('source_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declared_purities', to='core.sourcearea')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stream')),
            ],
            options={
                'unique_together': {('source_area', 'stream')},
            },
        ),
    ]
